name: Docker Image CI - Inove Bio
permissions:
  contents: read

on:
#   workflow_dispatch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: alexrese/inove-bio

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- PASSO NOVO E NECESSÁRIO ---
      # Este passo configura o Buildx, que habilita o suporte a cache avançado
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate dynamic version tag (date)
        id: generate_tag
        run: echo "VERSION_TAG=$(date +%d-%m-%Y)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
